### PR TITLE
Rename position

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #51

### CODE REVIEW

**Comment by littledan** [comment]
Thanks! Merging per resolution on #51

**Comment by anba** [comment]
This PR also changed the end index check in AdvanceSegmentIterator, was this intentional? 

Before this PR: 
```
1. If _direction_ is ~forwards~ and _position_ is the length of _string_, or if _direction_ is ~backwards~ and _position_ is *0*, return *true*.
```

Now:
```
1. Let _len_ be the length of _string_.
1. If _direction_ is ~forwards~ and _index_ is _len_ - 1, or if _direction_ is ~backwards~ and _index_ is *0*, return *true*.
```

**Comment by littledan** [comment]
I'm not sure how I missed that. @gibson042 what was the rationale for it? If we don't understand the rationale, let's revert this change. Does anyone want to make a PR?

**Comment by gibson042** [comment]
This relates directly to #52 and #59, but I believe that the original spec text was correct for the current model and that change should not have been made.

**Comment by littledan** [comment]
I see. OK, reverts welcome.

**Comment by gibson042** [comment]
PR: #61

**Pull request merged**
