### PR TITLE
Remove support for { granularity: 'line' }

### PR DESCRIPTION
**Pull request by mathiasbynens**
Closes #49.

### CODE REVIEW

**Comment by sffc** [comment]
Please don't merge this until we discuss in ECMA 402 subcommittee.

**Comment by FrankYFTang** [comment]
per 2019-1-17 ECMA 402 meeting discussion, we decided to take the line break out from the spec for now. Please also remove the "lb"in section 1.2.3 Internal slot as I mentioned above. Thanks

**Comment by littledan** [comment]
I'll merge this once @FrankYFTang 's comment is addressed.

**Comment by FrankYFTang** [comment]
v8 patch to remove the linebreak https://chromium-review.googlesource.com/c/v8/v8/+/1422749

**Comment by FrankYFTang** [comment]
Can we merge this PR first so it can unblock the landing of test262 tests.  I can create a follow up PR to take care the "lb" issue.

**Comment by FrankYFTang** [comment]
LGTM

**Pull request merged**
