### PR TITLE
Update from boundary iteration to segment iteration

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #80
Fixes #82
Fixes #83

* [x] `preceding`/`following` edge cases
* [x] spec text updates
* [x] update README

### CODE REVIEW

**Comment by gibson042** [comment]
The spec text in this PR is now ready; I'll update the README to match soon.

**Comment by gibson042** [comment]
Ready!

**Comment by sffc** [comment]
From October TC39 notes:

> Stage 3 volunteers needed for Intl segmenter - Philip Dunkel, Mark Cohen (both need mentors)
> Aki says there’s no conflict if Dan mentors

@littledan @pipobscure @mpcsh PTAL

**Comment by mpcsh** [comment]
👋 Happy to take a look here - will reach out to @littledan on IRC to try to set up a time for some mentorship.

**Comment by gibson042** [comment]
I'm going to merge this so the repository accurately reflects this proposal, but reviewers feel free to still comment here for maintaining context.

**Pull request merged**
