### PR TITLE
Mark the spec text as Stage 2

### PR DESCRIPTION
**Pull request by mathiasbynens**

### CODE REVIEW

**Comment by littledan** [comment]
It's actually Stage 3 at this point!

**Comment by littledan** [comment]
(Or, I thought it was...)

**Comment by mathiasbynens** [comment]
https://github.com/tc39/proposals says Stage 2, but could be wrong. Either way, let’s get this repo up-to-date :)

**Comment by littledan** [comment]
They both need to be updated; sorry, I'm a bit behind on my post-TC39 status update spraying. Anyway, this is an incremental improvement :).

**Pull request merged**
