### PR TITLE
Normative: Include position in segment object

### LINKED ISSUE #27: Should next() include a property with the position?
The String.prototype.codePoints proposal does. See also https://github.com/tc39/proposal-string-prototype-codepoints/issues/3

### PR DESCRIPTION
**Pull request by littledan**
The goal is to allow for easier usability and alignment with the
String.prototype.codePoints proposal.

By @FrankYFTang

Closes #27

### CODE REVIEW

**Comment by littledan** [comment]
cc @mathiasbynens

**Comment by FrankYFTang** [comment]
LGTM +1

**Comment by FrankYFTang** [comment]
once this PR is merged, I will try to land https://chromium-review.googlesource.com/c/v8/v8/+/1278636 into v8

**Comment by littledan** [comment]
OK, let's discuss it at the Intl meeting before merging.

**Comment by littledan** [comment]
We agreed on this PR in the Intl meeting, so merging it.

**Pull request merged**
